# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/luiscarlos/my_dev/projectESRG

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/luiscarlos/my_dev/projectESRG

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/luiscarlos/my_dev/projectESRG/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/luiscarlos/my_dev/projectESRG/CMakeFiles /home/luiscarlos/my_dev/projectESRG/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/luiscarlos/my_dev/projectESRG/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named smartFitness

# Build rule for target.
smartFitness: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 smartFitness
.PHONY : smartFitness

# fast build rule for target.
smartFitness/fast:
	$(MAKE) -f CMakeFiles/smartFitness.dir/build.make CMakeFiles/smartFitness.dir/build
.PHONY : smartFitness/fast

#=============================================================================
# Target rules for targets named smartFitness_autogen

# Build rule for target.
smartFitness_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 smartFitness_autogen
.PHONY : smartFitness_autogen

# fast build rule for target.
smartFitness_autogen/fast:
	$(MAKE) -f CMakeFiles/smartFitness_autogen.dir/build.make CMakeFiles/smartFitness_autogen.dir/build
.PHONY : smartFitness_autogen/fast

smartFitness_autogen/mocs_compilation.o: smartFitness_autogen/mocs_compilation.cpp.o

.PHONY : smartFitness_autogen/mocs_compilation.o

# target to build an object file
smartFitness_autogen/mocs_compilation.cpp.o:
	$(MAKE) -f CMakeFiles/smartFitness.dir/build.make CMakeFiles/smartFitness.dir/smartFitness_autogen/mocs_compilation.cpp.o
.PHONY : smartFitness_autogen/mocs_compilation.cpp.o

smartFitness_autogen/mocs_compilation.i: smartFitness_autogen/mocs_compilation.cpp.i

.PHONY : smartFitness_autogen/mocs_compilation.i

# target to preprocess a source file
smartFitness_autogen/mocs_compilation.cpp.i:
	$(MAKE) -f CMakeFiles/smartFitness.dir/build.make CMakeFiles/smartFitness.dir/smartFitness_autogen/mocs_compilation.cpp.i
.PHONY : smartFitness_autogen/mocs_compilation.cpp.i

smartFitness_autogen/mocs_compilation.s: smartFitness_autogen/mocs_compilation.cpp.s

.PHONY : smartFitness_autogen/mocs_compilation.s

# target to generate assembly for a file
smartFitness_autogen/mocs_compilation.cpp.s:
	$(MAKE) -f CMakeFiles/smartFitness.dir/build.make CMakeFiles/smartFitness.dir/smartFitness_autogen/mocs_compilation.cpp.s
.PHONY : smartFitness_autogen/mocs_compilation.cpp.s

src/applicationInterface.o: src/applicationInterface.cpp.o

.PHONY : src/applicationInterface.o

# target to build an object file
src/applicationInterface.cpp.o:
	$(MAKE) -f CMakeFiles/smartFitness.dir/build.make CMakeFiles/smartFitness.dir/src/applicationInterface.cpp.o
.PHONY : src/applicationInterface.cpp.o

src/applicationInterface.i: src/applicationInterface.cpp.i

.PHONY : src/applicationInterface.i

# target to preprocess a source file
src/applicationInterface.cpp.i:
	$(MAKE) -f CMakeFiles/smartFitness.dir/build.make CMakeFiles/smartFitness.dir/src/applicationInterface.cpp.i
.PHONY : src/applicationInterface.cpp.i

src/applicationInterface.s: src/applicationInterface.cpp.s

.PHONY : src/applicationInterface.s

# target to generate assembly for a file
src/applicationInterface.cpp.s:
	$(MAKE) -f CMakeFiles/smartFitness.dir/build.make CMakeFiles/smartFitness.dir/src/applicationInterface.cpp.s
.PHONY : src/applicationInterface.cpp.s

src/camera.o: src/camera.cpp.o

.PHONY : src/camera.o

# target to build an object file
src/camera.cpp.o:
	$(MAKE) -f CMakeFiles/smartFitness.dir/build.make CMakeFiles/smartFitness.dir/src/camera.cpp.o
.PHONY : src/camera.cpp.o

src/camera.i: src/camera.cpp.i

.PHONY : src/camera.i

# target to preprocess a source file
src/camera.cpp.i:
	$(MAKE) -f CMakeFiles/smartFitness.dir/build.make CMakeFiles/smartFitness.dir/src/camera.cpp.i
.PHONY : src/camera.cpp.i

src/camera.s: src/camera.cpp.s

.PHONY : src/camera.s

# target to generate assembly for a file
src/camera.cpp.s:
	$(MAKE) -f CMakeFiles/smartFitness.dir/build.make CMakeFiles/smartFitness.dir/src/camera.cpp.s
.PHONY : src/camera.cpp.s

src/exercise.o: src/exercise.cpp.o

.PHONY : src/exercise.o

# target to build an object file
src/exercise.cpp.o:
	$(MAKE) -f CMakeFiles/smartFitness.dir/build.make CMakeFiles/smartFitness.dir/src/exercise.cpp.o
.PHONY : src/exercise.cpp.o

src/exercise.i: src/exercise.cpp.i

.PHONY : src/exercise.i

# target to preprocess a source file
src/exercise.cpp.i:
	$(MAKE) -f CMakeFiles/smartFitness.dir/build.make CMakeFiles/smartFitness.dir/src/exercise.cpp.i
.PHONY : src/exercise.cpp.i

src/exercise.s: src/exercise.cpp.s

.PHONY : src/exercise.s

# target to generate assembly for a file
src/exercise.cpp.s:
	$(MAKE) -f CMakeFiles/smartFitness.dir/build.make CMakeFiles/smartFitness.dir/src/exercise.cpp.s
.PHONY : src/exercise.cpp.s

src/gui.o: src/gui.cpp.o

.PHONY : src/gui.o

# target to build an object file
src/gui.cpp.o:
	$(MAKE) -f CMakeFiles/smartFitness.dir/build.make CMakeFiles/smartFitness.dir/src/gui.cpp.o
.PHONY : src/gui.cpp.o

src/gui.i: src/gui.cpp.i

.PHONY : src/gui.i

# target to preprocess a source file
src/gui.cpp.i:
	$(MAKE) -f CMakeFiles/smartFitness.dir/build.make CMakeFiles/smartFitness.dir/src/gui.cpp.i
.PHONY : src/gui.cpp.i

src/gui.s: src/gui.cpp.s

.PHONY : src/gui.s

# target to generate assembly for a file
src/gui.cpp.s:
	$(MAKE) -f CMakeFiles/smartFitness.dir/build.make CMakeFiles/smartFitness.dir/src/gui.cpp.s
.PHONY : src/gui.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/smartFitness.dir/build.make CMakeFiles/smartFitness.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/smartFitness.dir/build.make CMakeFiles/smartFitness.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/smartFitness.dir/build.make CMakeFiles/smartFitness.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/mainwindow.o: src/mainwindow.cpp.o

.PHONY : src/mainwindow.o

# target to build an object file
src/mainwindow.cpp.o:
	$(MAKE) -f CMakeFiles/smartFitness.dir/build.make CMakeFiles/smartFitness.dir/src/mainwindow.cpp.o
.PHONY : src/mainwindow.cpp.o

src/mainwindow.i: src/mainwindow.cpp.i

.PHONY : src/mainwindow.i

# target to preprocess a source file
src/mainwindow.cpp.i:
	$(MAKE) -f CMakeFiles/smartFitness.dir/build.make CMakeFiles/smartFitness.dir/src/mainwindow.cpp.i
.PHONY : src/mainwindow.cpp.i

src/mainwindow.s: src/mainwindow.cpp.s

.PHONY : src/mainwindow.s

# target to generate assembly for a file
src/mainwindow.cpp.s:
	$(MAKE) -f CMakeFiles/smartFitness.dir/build.make CMakeFiles/smartFitness.dir/src/mainwindow.cpp.s
.PHONY : src/mainwindow.cpp.s

src/manageDB.o: src/manageDB.cpp.o

.PHONY : src/manageDB.o

# target to build an object file
src/manageDB.cpp.o:
	$(MAKE) -f CMakeFiles/smartFitness.dir/build.make CMakeFiles/smartFitness.dir/src/manageDB.cpp.o
.PHONY : src/manageDB.cpp.o

src/manageDB.i: src/manageDB.cpp.i

.PHONY : src/manageDB.i

# target to preprocess a source file
src/manageDB.cpp.i:
	$(MAKE) -f CMakeFiles/smartFitness.dir/build.make CMakeFiles/smartFitness.dir/src/manageDB.cpp.i
.PHONY : src/manageDB.cpp.i

src/manageDB.s: src/manageDB.cpp.s

.PHONY : src/manageDB.s

# target to generate assembly for a file
src/manageDB.cpp.s:
	$(MAKE) -f CMakeFiles/smartFitness.dir/build.make CMakeFiles/smartFitness.dir/src/manageDB.cpp.s
.PHONY : src/manageDB.cpp.s

src/poseClassification.o: src/poseClassification.cpp.o

.PHONY : src/poseClassification.o

# target to build an object file
src/poseClassification.cpp.o:
	$(MAKE) -f CMakeFiles/smartFitness.dir/build.make CMakeFiles/smartFitness.dir/src/poseClassification.cpp.o
.PHONY : src/poseClassification.cpp.o

src/poseClassification.i: src/poseClassification.cpp.i

.PHONY : src/poseClassification.i

# target to preprocess a source file
src/poseClassification.cpp.i:
	$(MAKE) -f CMakeFiles/smartFitness.dir/build.make CMakeFiles/smartFitness.dir/src/poseClassification.cpp.i
.PHONY : src/poseClassification.cpp.i

src/poseClassification.s: src/poseClassification.cpp.s

.PHONY : src/poseClassification.s

# target to generate assembly for a file
src/poseClassification.cpp.s:
	$(MAKE) -f CMakeFiles/smartFitness.dir/build.make CMakeFiles/smartFitness.dir/src/poseClassification.cpp.s
.PHONY : src/poseClassification.cpp.s

src/secondwindow.o: src/secondwindow.cpp.o

.PHONY : src/secondwindow.o

# target to build an object file
src/secondwindow.cpp.o:
	$(MAKE) -f CMakeFiles/smartFitness.dir/build.make CMakeFiles/smartFitness.dir/src/secondwindow.cpp.o
.PHONY : src/secondwindow.cpp.o

src/secondwindow.i: src/secondwindow.cpp.i

.PHONY : src/secondwindow.i

# target to preprocess a source file
src/secondwindow.cpp.i:
	$(MAKE) -f CMakeFiles/smartFitness.dir/build.make CMakeFiles/smartFitness.dir/src/secondwindow.cpp.i
.PHONY : src/secondwindow.cpp.i

src/secondwindow.s: src/secondwindow.cpp.s

.PHONY : src/secondwindow.s

# target to generate assembly for a file
src/secondwindow.cpp.s:
	$(MAKE) -f CMakeFiles/smartFitness.dir/build.make CMakeFiles/smartFitness.dir/src/secondwindow.cpp.s
.PHONY : src/secondwindow.cpp.s

src/training.o: src/training.cpp.o

.PHONY : src/training.o

# target to build an object file
src/training.cpp.o:
	$(MAKE) -f CMakeFiles/smartFitness.dir/build.make CMakeFiles/smartFitness.dir/src/training.cpp.o
.PHONY : src/training.cpp.o

src/training.i: src/training.cpp.i

.PHONY : src/training.i

# target to preprocess a source file
src/training.cpp.i:
	$(MAKE) -f CMakeFiles/smartFitness.dir/build.make CMakeFiles/smartFitness.dir/src/training.cpp.i
.PHONY : src/training.cpp.i

src/training.s: src/training.cpp.s

.PHONY : src/training.s

# target to generate assembly for a file
src/training.cpp.s:
	$(MAKE) -f CMakeFiles/smartFitness.dir/build.make CMakeFiles/smartFitness.dir/src/training.cpp.s
.PHONY : src/training.cpp.s

src/user.o: src/user.cpp.o

.PHONY : src/user.o

# target to build an object file
src/user.cpp.o:
	$(MAKE) -f CMakeFiles/smartFitness.dir/build.make CMakeFiles/smartFitness.dir/src/user.cpp.o
.PHONY : src/user.cpp.o

src/user.i: src/user.cpp.i

.PHONY : src/user.i

# target to preprocess a source file
src/user.cpp.i:
	$(MAKE) -f CMakeFiles/smartFitness.dir/build.make CMakeFiles/smartFitness.dir/src/user.cpp.i
.PHONY : src/user.cpp.i

src/user.s: src/user.cpp.s

.PHONY : src/user.s

# target to generate assembly for a file
src/user.cpp.s:
	$(MAKE) -f CMakeFiles/smartFitness.dir/build.make CMakeFiles/smartFitness.dir/src/user.cpp.s
.PHONY : src/user.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... package"
	@echo "... smartFitness"
	@echo "... smartFitness_autogen"
	@echo "... smartFitness_autogen/mocs_compilation.o"
	@echo "... smartFitness_autogen/mocs_compilation.i"
	@echo "... smartFitness_autogen/mocs_compilation.s"
	@echo "... src/applicationInterface.o"
	@echo "... src/applicationInterface.i"
	@echo "... src/applicationInterface.s"
	@echo "... src/camera.o"
	@echo "... src/camera.i"
	@echo "... src/camera.s"
	@echo "... src/exercise.o"
	@echo "... src/exercise.i"
	@echo "... src/exercise.s"
	@echo "... src/gui.o"
	@echo "... src/gui.i"
	@echo "... src/gui.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/mainwindow.o"
	@echo "... src/mainwindow.i"
	@echo "... src/mainwindow.s"
	@echo "... src/manageDB.o"
	@echo "... src/manageDB.i"
	@echo "... src/manageDB.s"
	@echo "... src/poseClassification.o"
	@echo "... src/poseClassification.i"
	@echo "... src/poseClassification.s"
	@echo "... src/secondwindow.o"
	@echo "... src/secondwindow.i"
	@echo "... src/secondwindow.s"
	@echo "... src/training.o"
	@echo "... src/training.i"
	@echo "... src/training.s"
	@echo "... src/user.o"
	@echo "... src/user.i"
	@echo "... src/user.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

